### ISSUE TITLE
Course creation issue arises again

### ISSUE THREAD

**Issue by duwhop** [inducer/relate#110]
Hello,  I apologize, but I am coming across the same error that I thought was fixed, but now has resurfaced. I am getting the WindowsError: [Error 32] again.  I decided to do the install again.

Traceback (most recent call last):
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\versioning.py", line 284, in set_up_new_course
    shutil.rmtree(repo_path, onerror=remove_readonly)
  File "C:\python27_x64\lib\shutil.py", line 248, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 248, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 248, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 253, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\versioning.py", line 281, in remove_readonly
    func(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'..\\Intro-to-CS\\.git\\objects\\pack\\pack-2f9dfef285660ede7712f891b20797569326bc96.idx'

I used the same advise that was given before by forking relate-sample repo and left the course root textfield blank, but still the same error.  Please help

**Comment by inducer** [comment]
Here's another attempt at a fix: ca116d88. (In current `master`.) Let me know if that works.

**Comment by duwhop** [comment]
Awesome.  That did it!  No WindowsError message.  Thanks a whole bunch!
