### ISSUE TITLE
Application labels aren't unique, duplicates: djcelery

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#140]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 208, in handle
    changes = autodetector.changes(graph=executor.loader.graph)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/autodetector.py", line 110, in _detect_changes
    self.old_apps = self.from_state.concrete_apps
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/state.py", line 170, in concrete_apps
    self.apps = StateApps(self.real_apps, self.models, ignore_swappable=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/state.py", line 230, in __init__
    super(StateApps, self).__init__(app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 56, in __init__
    self.populate(installed_apps)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: djcelery
```

This issue prevent me from migrating on linux, while it work on windows. ``migrate --fake`` won't work. see same report but failed.
http://stackoverflow.com/questions/28766841/error-in-migration-of-django-app-using-celery

**Comment by dzhuang** [comment]
Sorry, it's my fault. Solved by removing migration files other than ``__init__.py`` and ``0001_inital.py``, in ``/urser/local/lib/python2.7/dist-packages/djcelery/migrations/``. There were other auto generated migration files which cause the issue.

**Comment by inducer** [comment]
Happy to hear you got it sorted.
