### ISSUE TITLE
Error on failing to create new course on Windows

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#16]
```
[03/May/2015 14:18:48]"POST /new-course/ HTTP/1.1" 200 10638
Traceback (most recent call last):
  File "F:\tempgit\forLocale\relate\course\versioning.py", line 192, in set_up_new_course
    shutil.rmtree(repo_path)
  File "d:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "d:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "d:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "d:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "d:\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] : u'..\\demo\\.git\\objects\\pack\\pack-2e0d43fe4bf649ad323e3734efc2f3cd7ae7c71c.idx'
```

I see this <http://stackoverflow.com/questions/1889597/deleting-directory-in-python/1889686#1889686>.

**Comment by inducer** [comment]
Thanks for the report.

**Comment by dzhuang** [comment]
Sorry, I tested the commit and find it still fail, and recently there is a PR of dulwich on this issue https://github.com/jelmer/dulwich/pull/275

**Comment by inducer** [comment]
The dulwich fix is the same as what I applied. Compare

* [theirs](/garyvdm/dulwich/commit/e82020ced4)
* [ours](/inducer/relate/commit/ee74654a4b)

Can you provide a backtrace for the current failure you're seeing? It's not shown in the web UI, but it is printed to stdout.

**Comment by dzhuang** [comment]
```
Traceback (most recent call last):
  File "E:\git-trial\course\relate-upstream\course\versioning.py", line 204, in set_up_new_course
    shutil.rmtree(repo_path, onerror=remove_readonly)
  File "d:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "d:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "d:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "d:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "E:\git-trial\course\relate-upstream\course\versioning.py", line 202, in remove_readonly
    func(path)
WindowsError: [Error 32] : u'D:\\document\\python\\course\\course-git\\wrong-demo\\.git\\objects\\pack\\pack-4f895822e704069af564b75b5ee68785063429ed.idx'
```

Now I think the problem is the directory is "In use" so that it failed to remove, as I use windows shell command `RD path/to/remove /S /Q ` (`deltree` equivalent in windows 7 shell), it prompt an exception that the .idx file and .pack file are currently used by another session, and cannot be deleted.

**Comment by dzhuang** [comment]
Seem I will have to terminate the server and proceed to delete the folder manually under windows.  If this is true, my suggestion is to skip the deleting process for windows user and proceed to inform them about the validation errors, which is more important.

**Comment by inducer** [comment]
Try 89caa15. I've tried to make sure that all the resources associated with the failed repo are freed. In theory, that should close all the files.

**Comment by dzhuang** [comment]
Thank you, I will report the result after test.

**Comment by dzhuang** [comment]
Without success, with the same output.

**Comment by inducer** [comment]
Alright, I'm sick of it. I've made this a non-critical failure that shows a message in 7059345. We'll leave this for the user to mop up.
