### ISSUE TITLE
How does the RELATE command work?

### ISSUE THREAD

**Issue by samtux** [inducer/relate#349]
I am trying to validate the YAML files, but I would like to know how the RELATE command works.

```
> relate validate /srv/git/sig-20173/
```

It always generates the error with:

```
Traceback (most recent call last):
  File "/usr/local/bin/relate", line 4, in <module>
...
File "/usr/local/lib/python3.5/dist-packages/relate_courseware-2016.1-py3.5.egg/course/content.py", line 39, in <module>
    from django.urls import NoReverseMatch
ImportError: No module named 'django.urls'
```

**Comment by inducer** [comment]
Did you install using `setup.py`?

**Comment by samtux** [comment]
Sorry, I did not install pip requirements before. Now everything works correctly.
