### ISSUE TITLE
Reduce errors connecting to container

### ISSUE THREAD

**Issue by lukeolson** [inducer/relate#357]
I’m seeing a handful of these a day.  I think they should only a trigger a message if the connection issue happens multiple times in a row. Any thoughts on implementing this?

```
RESULT: uncaught_error
-------------------------------------
message
-------------------------------------
Error connecting to container
-------------------------------------
traceback
-------------------------------------
Traceback (most recent call last):
 File "./course/page/code.py", line 629, in grade
   run_timeout=self.page_desc.timeout)
 File "./course/page/code.py", line 284, in request_python_run_with_retries
   result = request_python_run(run_req, run_timeout, image=image)
 File "./course/page/code.py", line 218, in request_python_run
   http_response = connection.getresponse()
 File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
   response.begin()
 File "/usr/lib/python3.5/http/client.py", line 297, in begin
   version, status, reason = self._read_status()
 File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
   raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by inducer** [comment]
I'll wait for the build to pass and then take this live on relate.cs.

**Comment by inducer** [comment]
Done.
