### ISSUE TITLE
Out of memory inside of a container not cleanly diagnosed

### ISSUE THREAD

**Issue by inducer** [inducer/relate#539]
It used to just time out. Now it seems to be possible that the OOM killer gets these processes and we may get this instead:

```
Traceback (most recent call last):
  File "./course/page/code.py", line 635, in grade
    run_timeout=self.page_desc.timeout)
  File "./course/page/code.py", line 288, in request_python_run_with_retries
    result = request_python_run(run_req, run_timeout, image=image)
  File "./course/page/code.py", line 220, in request_python_run
    http_response = connection.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

Which is tough from a grading perspective, since it doesn't assign fault.

**Comment by isuruf** [comment]
Adding the following to the setup code gives a graceful failure
```
import resource
resource.setrlimit(resource.RLIMIT_AS,(10**9, 10**9))
```

**Comment by inducer** [comment]
That's a good suggestion. We could just have the app server stick the container-side memory limit into the submission JSON and have the runner component set the resource limit, so that this is not the user's responsibility.
