### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by wisnercelucus** [inducer/relate#594]
First, thank you for this marvelous LMS. I was able to follow the documentation and launch the application locally. It works fine. However, I wanted to test the enrollment functionality. I cannot enroll because the connection is not allowed "No connection could be made because the target machine actively refused it". I know that it has nothing to do with the code, but can you please help me figure out how to resolve this issue? I am on windows 10. 
Thank you for your help.

**Comment by inducer** [comment]
Hmm, could you help me understand in what situation you are seeing this? (e.g. post a screenshot before and after if nothing else.)

If this is your browser refusing the connection, maybe there's a backtrace somewhere in the terminal where it ran. If so, copy-pasting that would help tremendously in figuring out what went wrong. Also, thank you for taking the time to report your issue!

**Comment by wisnercelucus** [comment]
Ok, thank you for your prompt answer!
Here is a copy of the error message:

Internal Server Error: /course/monitoring-and-evaluation/enroll/
Traceback (most recent call last):
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\Lib\contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "C:\Users\Wisner CELUCUS\Desktop\Django\tiy\tiy\relate\course\enrollment.py", line 303, in enroll_view
    msg.send()
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\mail\message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\mail\backends\smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\mail\backends\smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "C:\ProgramData\Anaconda3\Lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\ProgramData\Anaconda3\Lib\smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\ProgramData\Anaconda3\Lib\smtplib.py", line 306, in _get_socket
    self.source_address)
  File "C:\ProgramData\Anaconda3\Lib\socket.py", line 722, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\Lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
[04/Aug/2018 19:11:04] "POST /course/monitoring-and-evaluation/enroll/ HTTP/1.1" 500 131997

**Comment by wisnercelucus** [comment]
![image](https://user-images.githubusercontent.com/26372332/43681501-e0a56d38-981a-11e8-8335-4ec178e1df5e.png)

**Comment by inducer** [comment]
Oh! It's trying to send email, by connecting to port 25 on your local machine. (and failing with a non-useful message when that doesn't work) Filling out the email configuration in `local_settings.py` should get you on your way. In the meantime, let's leave this open as a reminder to improve these error messages.

**Comment by wisnercelucus** [comment]
Hi again. Thank you for your help. I was trying to configure the local_settings.py but the error persists:
Let me know how to improve it, this task is not my cup of coffee ... hahah....

# {{{ email

EMAIL_HOST = '127.0.0.1'
EMAIL_HOST_USER = 'I don't know what to put here!!!'
EMAIL_HOST_PASSWORD = 'I added my gmail password here, is that right?'
EMAIL_PORT = 25
EMAIL_USE_TLS = False

ROBOT_EMAIL_FROM = "wisnercelicus@gmail.com"
RELATE_ADMIN_EMAIL_LOCALE = "en_US"

SERVER_EMAIL = ROBOT_EMAIL_FROM

ADMINS = (
    ("wisnercelicus@gmail.com",), #I added my admin email address here.
    )

# If your email service do not allow nonauthorized sender, uncomment the following
# statement and change the configurations above accordingly, noticing that all
# emails will be sent using the EMAIL_ settings above.
#RELATE_EMAIL_SMTP_ALLOW_NONAUTHORIZED_SENDER = False

# Advanced email settings if you want to configure multiple SMTPs for different
# purpose/type of emails. It is also very useful when
# "RELATE_EMAIL_SMTP_ALLOW_NONAUTHORIZED_SENDER" is False.
# If you want to enable this functionality, set the next line to True, and edit
# the next block with your cofigurations.
RELATE_ENABLE_MULTIPLE_SMTP = False

if RELATE_ENABLE_MULTIPLE_SMTP:
    EMAIL_CONNECTIONS = {

        # For automatic email sent by site.
        "robot": {
            # You can use your preferred email backend.
            'backend': 'djcelery_email.backends.CeleryEmailBackend',
            'host': 'smtp.gmail.com',
            'username': 'wisnercelicus@gmail.com', 
            'password': 'password',
            'port': 587,
            'use_tls': True,
        },

        # For emails that expect no reply for recipients, e.g., registration,
        # reset password, etc.
        "no_reply": {
            'host': 'smtp.gmail.com',
            'username': 'blah@blah.com',
            'password': 'password',
            'port': 587,
            'use_tls': True,
        },

        # For sending notifications like submission of flow sessions.
        "notification": {
            'host': 'smtp.gmail.com',
            'username': 'blah@blah.com',
            'password': 'password',
            'port': 587,
            'use_tls': True,
        },

        # For sending feedback email to students in grading interface.
        "grader_feedback": {
            'host': 'smtp.gmail.com',
            'username': 'blah@blah.com',
            'password': 'password',
            'port': 587,
            'use_tls': True,
        },

        # For student to send email to course staff in flow pages
        "student_interact": {
            'host': 'smtp.gmail.com',
            'username': 'blah@blah.com',
            'password': 'password',
            'port': 587,
            'use_tls': True,
        },

        # For enrollment request email sent to course instructors
        "enroll": {
            'host': 'smtp.gmail.com',
            'username': 'wisnercelicus@gmail.com',
            'password': 'password',
            'port': 587,
            'use_tls': True,
        },
    }

    # This will be used as default connection when other keys are not set.
    EMAIL_CONNECTION_DEFAULT = "robot"

    NO_REPLY_EMAIL_FROM = "Noreply <noreply_example@example.com>"
    NOTIFICATION_EMAIL_FROM = "Notification <notification_example@example.com>"
    GRADER_FEEDBACK_EMAIL_FROM = "Feedback <feedback_example@example.com>"
    STUDENT_INTERACT_EMAIL_FROM = "interaction <feedback_example@example.com>"
    ENROLLMENT_EMAIL_FROM = "Enrollment <enroll@example.com>"


# }}}

**Comment by inducer** [comment]
```
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'your.email@gmail.com'
EMAIL_HOST_PASSWORD = 'gmail password'
EMAIL_PORT = 25
EMAIL_USE_TLS = True  # definitely true here
```

**Comment by wisnercelucus** [comment]
Wow wow wow! it works! Thank you so much! beautiful package. I will definitely work on the home page to add search functionality and also, course categories and author staff to enhance to the user experience. Thank you, your package is strong!
