### ISSUE TITLE
make relate and mezzanine work together

### ISSUE THREAD

**Issue by wisnercelucus** [inducer/relate#595]
Hi, Inducer!
Now I am trying to integrate relate with mezzanine. After installing mezzanine with pip. I add it in the installed app. I merged all the settings so that all the variables of mezzanine are listed in the settings.py file in the relate directory. I then import mezzanine in the urls.py of relate. I added right bellow `url(r'^admin', admin.site.urls)`  the route to reach mezzanine. like this `url(r'^social/',include('mezzanine.urls'))` . When I run python manage.py migrate: I got this error:

```
(tiy) C:\Users\Wisner CELUCUS\Desktop\Django\tiy\tiy\relate>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 54, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\base.py", line 327, in execute
    self.check()
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\commands\migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Wisner CELUCUS\Desktop\Django\tiy\tiy\relate\relate\urls.py", line 556, in <module>
    url(r'^admin/', admin.site.urls),
  File "C:\Users\WISNER~2\Desktop\Django\tiy\lib\site-packages\django\conf\urls\__init__.py", line 80, in url
    urlconf_module, app_name, namespace = view
ValueError: too many values to unpack (expected 3)

(tiy) C:\Users\Wisner CELUCUS\Desktop\Django\tiy\tiy\relate>
```

Can you help me figure out what I have done badly? or do you know an easy way to integrate Mezzanine & cartridge (for blog, about, galery, shop, ...) and SPIRIT (FORUM) and make them all working together? 

That would save my life. Thaink you for your help.

Thank you for your support!

**Comment by inducer** [comment]
Sorry, no idea. I would start by looking at the Django docs. There was a compatibility break recently regarding urlconfs.
