### ISSUE TITLE
After installation, cannot add the example course.

### ISSUE THREAD

**Issue by vi** [inducer/relate#65]
It says:

```
Course creation failed: ValidationError: flows/quiz-test.yml, group 3 ('quiz_tail'), page 12 ('excelbasictry3'): could not instantiate flow page: ValueError: Extension "__builtin__.NoneType" must be of type: "markdown.Extension".

Traceback (most recent call last):
  File "/mnt/src/git/relate/course/validation.py", line 349, in validate_flow_page
    class_(ctx, location, page_desc)
  File "/mnt/src/git/relate/course/page/inline.py", line 691, in __init__
    text=page_desc.question,
  File "/mnt/src/git/relate/course/content.py", line 577, in markup_to_html
    output_format="html5")
  File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 395, in markdown
    md = Markdown(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 134, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 166, in registerExtensions
    % (ext.__class__.__module__, ext.__class__.__name__))
ValueError: Extension "__builtin__.NoneType" must be of type: "markdown.Extension".
```

**Comment by inducer** [comment]
What version of Python-Markdown are you using?

**Comment by vi** [comment]
~~I don't know, probably the one from `requirements.txt`.~~

---

I was using site version of python-markdown because of virtualenv was created (per [installation guide](http://documen.tician.de/relate/misc.html#installation)) with `--system-site-packages`. After `pip install markdown` it works.

Maybe the guide should be changed, omitting `--system-site-packages`?

**Comment by inducer** [comment]
Done, thanks for the suggestion.
