### ISSUE TITLE
502 when large amount of sessions started at around the same time.

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#740]
About 250 students started their sessions at the same time (to start an instant flow in class), 502 errors were reported from most students, for around 15 miniutes. CPU usage was reported to be around 100%. Maybe the reason was the low processing capacity of my server?

The following Traceback were sent to admin email.

```
Traceback (most recent call last):
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

The above exception (ERROR:  Could not serialize access due to read/write dependencies among transactions.
DETAIL:  Reason code: Canceled on identification as a pivot, during conflict out checking.
HINT:  The transaction might succeed if retried.
) was the direct cause of the following exception:
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/course/relate/course/utils.py", line 792, in wrapper
    response = f(pctx, *args, **kwargs)
  File "/home/course/relate/course/flow.py", line 1386, in view_start_flow
    return post_start_flow(pctx, fctx, flow_id)
  File "./relate/utils.py", line 333, in wrapper
    serializable=self.serializable)
  File "./relate/utils.py", line 309, in retry_transaction
    return f(*args, **kwargs)
  File "/home/course/relate/course/flow.py", line 1526, in post_start_flow
    now_datetime=now_datetime)
  File "/home/course/relate/course/flow.py", line 453, in start_flow
    course.identifier, flow_desc, respect_preview=True)
  File "/home/course/relate/course/flow.py", line 307, in adjust_flow_session_page_data
    commit_sha)
  File "./relate/utils.py", line 333, in wrapper
    serializable=self.serializable)
  File "./relate/utils.py", line 309, in retry_transaction
    return f(*args, **kwargs)
  File "/home/course/relate/course/flow.py", line 210, in _adjust_flow_session_page_data_inner
    .order_by("page_ordinal")):
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/course/relate/.venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

Exception Type: OperationalError at /course/cesim2020/flow/quiz/start/
Exception Value: ERROR:  Could not serialize access due to read/write dependencies among transactions.
DETAIL:  Reason code: Canceled on identification as a pivot, during conflict out checking.
HINT:  The transaction might succeed if retried.
```

**Comment by inducer** [comment]
First, the exception you're showing is allowed/supposed to happen. If you limit the number of sessions per student, then to carry out the (how many sessions do you have? OK, you're allowed to create one) step in a serializable manner, the database has to check if any intermediate results that were visible to the application have been changed in a concurrent transation. If so, it aborts the current transaction.

So, these happen on my instance as well. However, they don't seem to happen with the severity you describe. When a few hundred students start an exam at the same time, I might get five or so emails, the students reload the page, and everything resolves in less than a minute. That's why I've never dug particularly deeply into this. I suspect that, in your case, the database was lagging behind substantially, and it just never c

Technically, unless a student is trying to 'try something funny' (not the default case I suppose), the transactions should actually be independent (because they concern different participants). I don't know why the DBMS doesn't realize this, but I would be eager to find out.

**Comment by dzhuang** [comment]
Thanks for the prompt response!

Actually, I just got 1 email.
> So, these happen on my instance as well. However, they don't seem to happen with the severity you describe. When a few hundred students start an exam at the same time, I might get five or so emails,

I think the 502 and the exception above were kind of independent, since the 502 page were displayed almost promptly. Is it possible that the number of nginx workers were few in number as compared with the amount of starting flow requests, so that the server was overloaded?

**Comment by inducer** [comment]
I think that's a plausible theory. I run with a fair number of uwsgi worker processes (I can look if you're interested), and I think they auto-scale in response to demand.

**Comment by dzhuang** [comment]
Thanks for the response. I think that's the reason. I'm now closing the issue.
